### PR TITLE
Spell-fix: "emumerations" to "enumerations"

### PR DESCRIPTION
**Pull request by felixlinker**

### CODE REVIEW

**Comment by nikku** [comment]
Could you adjust your PR to use a commit message en par with our [commit message guidelines](https://github.com/bpmn-io/bpmn-js/blob/master/docs/project/COMMIT_MESSAGES.md)? Something like

```
fix(parser): correct typo
```

would work.

**Comment by felixlinker** [comment]
If you tell me how to do that 😁 I tried googling it but didn't found any helpful explanation. I guess, since I'm working on a patch, I'd have to re-open this PR with the commit message set accordingly?

**Comment by nikku** [comment]
You'd do the following:

* On your feature branch, rebase (`git rebase -i HEAD~1`) the last commit.
* Specify `r` for rewriting it.
* Git will rewrite the last commits message.
* Force push onto the remote branch; this will update this PR

**Comment by nikku** [comment]
Will do it myself, no worries :wink:.

**Comment by nikku** [comment]
Merged via https://github.com/bpmn-io/cmof-parser/commit/32f1d56166802b001167c8dccbacf74c469d6f3d. Thanks.

**Pull request closed without merging**
